name = "nyctailblazers-subdomain-router"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
account_id = "4589ead053bd6785d78f5096068625ba"

routes = [
  { pattern = "*.nyctailblazers.com/*", zone_name = "nyctailblazers.com" }
]
